
start-redpanda:
	docker-compose -f docker-compose.yml up -d

stop-redpanda:
	docker-compose -f docker-compose.yml down

run-feature-pipeline:
	docker compose -f feature-pipeline.yml up 

stop-feature-pipeline:
	docker compose -f feature-pipeline.yml down