version: '3.8'

name: feature_pipeline

networks:
  redpanda_network:
    name: redpanda_network
    driver: bridge

services:
  trade-producer:
    build:
      context: ../services/trade-producer
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
      KAFKA_OUTPUT_TOPIC: trade_backfill
      LIVE_OR_HISTORICAL: historical
      PRODUCT_IDS: '["BTC/EUR", "ETH/EUR"]'
      LAST_N_DAYS: 1
      CACHE_DIR_PATH: /tmp/cached_backfill
    ports:
      - "8001:8001"
    restart:
      on-failure

  trade-to-ohlc:
    build:
      context: ../services/trade-to-ohlc
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
      KAFKA_INPUT_TOPIC: trade_backfill
      KAFKA_OUTPUT_TOPIC: ohlc_backfill
      AUTO_OFFSET_RESET: earliest
      OHLC_WINDOW_SECONDS: 10
      CONSUMER_GROUP: trade-to-ohlc-backfill
    ports:
      - "8002:8002"
    restart:
      always

  kafka-to-feature:
    build:
      context: ../services/kafka-to-store
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
      KAFKA_INPUT_TOPIC: ohlc_backfill
      KAFKA_CONSUMER_GROUP: kafka-to-store-backfill
      AUTO_OFFSET_RESET: earliest
      HOPSWORK_PROJECT_NAME: ml_system_c1
      HOPSWORK_FEATURE_GROUP_NAME: candles_fgap
      HOPSWORK_FEATURE_GROUP_VERSION: 1
      ONLINE_OFFLINE: offline
      BUFFER_SIZE: 100
      TIMER: 10

    env_file:
      - ../services/kafka-to-store/.credentials.env
    ports:
      - "8003:8003"
    restart:
      always